// <auto-generated />
using LernPlattform.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LernPlattform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905195443_KursBeschreibung")]
    partial class KursBeschreibung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LernPlattform.Domain.Entities.Fachgebiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fachgebiete");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bezeichnung = "Projektmanagement",
                            Reihenfolge = 1
                        },
                        new
                        {
                            Id = 2,
                            Bezeichnung = "Modellierung",
                            Reihenfolge = 2
                        },
                        new
                        {
                            Id = 3,
                            Bezeichnung = "Projektprüfung",
                            Reihenfolge = 3
                        },
                        new
                        {
                            Id = 4,
                            Bezeichnung = "Hardware",
                            Reihenfolge = 4
                        },
                        new
                        {
                            Id = 5,
                            Bezeichnung = "Betriebssysteme",
                            Reihenfolge = 5
                        },
                        new
                        {
                            Id = 6,
                            Bezeichnung = "Software und KI",
                            Reihenfolge = 6
                        },
                        new
                        {
                            Id = 7,
                            Bezeichnung = "Netzwerk",
                            Reihenfolge = 7
                        },
                        new
                        {
                            Id = 8,
                            Bezeichnung = "Netzwerkdienste",
                            Reihenfolge = 8
                        },
                        new
                        {
                            Id = 9,
                            Bezeichnung = "Cloud und Virtualisierung",
                            Reihenfolge = 9
                        },
                        new
                        {
                            Id = 10,
                            Bezeichnung = "IT-Sicherheit",
                            Reihenfolge = 10
                        },
                        new
                        {
                            Id = 11,
                            Bezeichnung = "Datenschutz",
                            Reihenfolge = 11
                        },
                        new
                        {
                            Id = 12,
                            Bezeichnung = "Storage und Backup",
                            Reihenfolge = 12
                        },
                        new
                        {
                            Id = 13,
                            Bezeichnung = "Verfügbarkeit",
                            Reihenfolge = 13
                        },
                        new
                        {
                            Id = 14,
                            Bezeichnung = "Systemadministration",
                            Reihenfolge = 14
                        },
                        new
                        {
                            Id = 15,
                            Bezeichnung = "Programmierung",
                            Reihenfolge = 15
                        },
                        new
                        {
                            Id = 16,
                            Bezeichnung = "Datenbanken",
                            Reihenfolge = 16
                        },
                        new
                        {
                            Id = 17,
                            Bezeichnung = "Softwarearchitektur",
                            Reihenfolge = 17
                        },
                        new
                        {
                            Id = 18,
                            Bezeichnung = "Softwarequalität",
                            Reihenfolge = 18
                        },
                        new
                        {
                            Id = 19,
                            Bezeichnung = "Benutzeroberfläche",
                            Reihenfolge = 19
                        },
                        new
                        {
                            Id = 20,
                            Bezeichnung = "Schnittstellen und Web",
                            Reihenfolge = 20
                        },
                        new
                        {
                            Id = 21,
                            Bezeichnung = "Werkzeuge und DevOps",
                            Reihenfolge = 21
                        },
                        new
                        {
                            Id = 22,
                            Bezeichnung = "Cyber-physische Systeme",
                            Reihenfolge = 22
                        },
                        new
                        {
                            Id = 23,
                            Bezeichnung = "BWL",
                            Reihenfolge = 23
                        },
                        new
                        {
                            Id = 24,
                            Bezeichnung = "WiSo",
                            Reihenfolge = 24
                        },
                        new
                        {
                            Id = 25,
                            Bezeichnung = "Recht und Lizenzen",
                            Reihenfolge = 25
                        },
                        new
                        {
                            Id = 26,
                            Bezeichnung = "Nachhaltigkeit",
                            Reihenfolge = 26
                        },
                        new
                        {
                            Id = 27,
                            Bezeichnung = "Service und Support",
                            Reihenfolge = 27
                        },
                        new
                        {
                            Id = 28,
                            Bezeichnung = "Kommunikation",
                            Reihenfolge = 28
                        });
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Farbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAktiv")
                        .HasColumnType("bit");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kurse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschreibung = "AP1, AP2 und Wiso",
                            Bezeichnung = "Fachinformatiker Baden-Württemberg",
                            Farbe = "#1F3864",
                            IsAktiv = false,
                            Reihenfolge = 1
                        });
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Pruefungsbereich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Farbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kuerzel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.ToTable("Pruefungsbereiche");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschreibung = "Teil 1 der gestreckten Abschlussprüfung",
                            Farbe = "#2E5395",
                            Kuerzel = "AP1",
                            KursId = 1,
                            Reihenfolge = 1,
                            Titel = "Einrichten eines IT-gestützten Arbeitsplatzes"
                        },
                        new
                        {
                            Id = 2,
                            Beschreibung = "Teil 2 – Fachrichtung Systemintegration",
                            Farbe = "#1B7F5C",
                            Kuerzel = "AP2",
                            KursId = 1,
                            Reihenfolge = 2,
                            Titel = "Systemintegration"
                        },
                        new
                        {
                            Id = 3,
                            Beschreibung = "Teil 2 – Fachrichtung Anwendungsentwicklung",
                            Farbe = "#A34700",
                            Kuerzel = "AP2",
                            KursId = 1,
                            Reihenfolge = 3,
                            Titel = "Anwendungsentwicklung"
                        },
                        new
                        {
                            Id = 4,
                            Beschreibung = "Teil 2 – 10 Prozent der Gesamtnote",
                            Farbe = "#6B4C9A",
                            Kuerzel = "WiSo",
                            KursId = 1,
                            Reihenfolge = 4,
                            Titel = "Wirtschafts- und Sozialkunde"
                        });
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Thema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FachgebietId")
                        .HasColumnType("int");

                    b.Property<string>("Lernfeld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PruefungsbereichId")
                        .HasColumnType("int");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FachgebietId");

                    b.ToTable("Themen");
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Pruefungsbereich", b =>
                {
                    b.HasOne("LernPlattform.Domain.Entities.Kurs", "Kurs")
                        .WithMany("Bereiche")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Thema", b =>
                {
                    b.HasOne("LernPlattform.Domain.Entities.Fachgebiet", "Fachgebiet")
                        .WithMany("Themen")
                        .HasForeignKey("FachgebietId");

                    b.Navigation("Fachgebiet");
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Fachgebiet", b =>
                {
                    b.Navigation("Themen");
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Kurs", b =>
                {
                    b.Navigation("Bereiche");
                });
#pragma warning restore 612, 618
        }
    }
}
