// <auto-generated />
using LernPlattform.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LernPlattform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LernPlattform.Domain.Entities.Pruefungsbereich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Farbe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kuerzel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pruefungsbereiche");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschreibung = "Teil 1 der gestreckten Abschlussprüfung",
                            Farbe = "#2E5395",
                            Kuerzel = "AP1",
                            Reihenfolge = 1,
                            Titel = "Einrichten eines IT-gestützten Arbeitsplatzes"
                        },
                        new
                        {
                            Id = 2,
                            Beschreibung = "Teil 2 – Fachrichtung Systemintegration",
                            Farbe = "#1B7F5C",
                            Kuerzel = "AP2",
                            Reihenfolge = 2,
                            Titel = "Systemintegration"
                        },
                        new
                        {
                            Id = 3,
                            Beschreibung = "Teil 2 – Fachrichtung Anwendungsentwicklung",
                            Farbe = "#A34700",
                            Kuerzel = "AP2",
                            Reihenfolge = 3,
                            Titel = "Anwendungsentwicklung"
                        });
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Thema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PruefungsbereichId")
                        .HasColumnType("int");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PruefungsbereichId");

                    b.ToTable("Themen");
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Thema", b =>
                {
                    b.HasOne("LernPlattform.Domain.Entities.Pruefungsbereich", "Pruefungsbereich")
                        .WithMany("Themen")
                        .HasForeignKey("PruefungsbereichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pruefungsbereich");
                });

            modelBuilder.Entity("LernPlattform.Domain.Entities.Pruefungsbereich", b =>
                {
                    b.Navigation("Themen");
                });
#pragma warning restore 612, 618
        }
    }
}
